name: "Liym Lab "
description: "This is the official web page for Yumei Li's lab at Soochow University."

url: "https://liymlab.github.io/"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
