name: "Rege Lab "
description: "This is the official web page for Mayuri Rege at Ruia College, Mumbai."

url: "https://regelab.github.io"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
