name: "Li Lab "

url: "https://LiymLab.github.io"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
